server:
  protocol: http
  host: 0.0.0.0
  port: 3000
  options:
    - name: logger
      value: true

views:
  templatesPath: ../views
  layout: _layout
  includeViewExtension: true
  engineOptions:
    async: true
    htmlMinifierOptions:
      removeComments: true
      removeCommentsFromCDATA: true
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeEmptyAttributes: true
      minifyCSS: true
      minifyJS: true

assets:
  rootPath: ../public
  options:
    prefix: /public/
    cacheControl: true
    etag: true
    acceptRanges: true
    lastModified: true
    maxAge: 86400000

##
# Configuration for file upload input inside ../views/upload.hbs
#
# - accept property is
#    an array of the **template value** from https://www.iana.org/assignments/media-types/media-types.xhtml
#    or */* to allow all types
#
# Configuration for API endpoint
#
# - fileEndpoint is the endpoint to upload file(s)
# - method The HTTP Method to use for the request. Only `POST` and `PUT` are allowed. Change it only if your own API wants a PUT instead of a POST
#
# Configuration for additional FormData
#
# - additionalFormData is an object to add custom data inside the FormData and send it to the server
#
#   - fieldName is the key of the custom data inside the FormData
#   - data is an object or a string representing the value of this custom data.
#
#  This custom data will be automatically serialized before inserted inside the FormData with formData.append(fieldName,JSON.stringify(data))
##
upload:
  input:
    accept:
      - application/pdf
      - image/*
#      - video/*
  api:
    fileEndpoint: /api/upload
    method: POST
#  additionalFormData:
#    fieldName: myAdditionalFormData
#    data:
#      first: true
#      second: itsAString
#      third:
#        key1: thirdItsAnObject1
#        key2: thirdItsAnObject2
